# Generated by Django 4.0.4 on 2022-04-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40, verbose_name='好きな色')),
                ('food', models.CharField(max_length=40, verbose_name='好きな食べ物')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_name', to='test_app.test', verbose_name='名前')),
            ],
            options={
                'verbose_name_plural': 'TestPersonal',
            },
        ),
    ]
